server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/java
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.hikari.schema=catsapp_cats

spring.jpa.hibernate.ddl-auto=update

spring.flyway.schemas=catsapp_cats
spring.flyway.locations=classpath:/migrations
spring.flyway.validate-migration-naming=true