CREATE SCHEMA IF NOT EXISTS catsapp_cats;

CREATE TABLE IF NOT EXISTS cataApp_cats.cats (
    id      bigint GENERATED BY DEFAULT AS IDENTITY,
    name        varchar(255) NOT NULL,
    breed       varchar(255),
    color       varchar(255),
    birthdate   date,
    owner_id    bigint,
    PRIMARY KEY (id),
    CONSTRAINT cats_color_check
    CHECK (color::text = ANY
    (ARRAY
    [
           'BLACK'::character varying,
           'WHITE'::character varying,
           'GREY'::character varying,
           'ORANGE'::character varying,
           'SEMICOLOR'::character varying,
           'BLACK_WHITE'::character varying
    ]::text[])
    )
);

CREATE TABLE IF NOT EXISTS catsApp_cats.friends (
    first_cat_id    bigint NOT NULL REFERENCES catsapp_cats.cats(id),
    second_cat_id   bigint NOT NULL REFERENCES catsapp_cats.cats(id),
    PRIMARY KEY (first_cat_id, second_cat_id)
);