CREATE TABLE IF NOT EXISTS owners (
                                             id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             first_name  VARCHAR(255) NOT NULL,
    last_name   VARCHAR(255) NOT NULL,
    birthdate   DATE NOT NULL
    );

CREATE TABLE IF NOT EXISTS cats (
                                           id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           name      VARCHAR(255) NOT NULL,
    birthdate DATE NOT NULL,
    breed     VARCHAR(255) NOT NULL,
    color     VARCHAR(50) NOT NULL,
    owner_id  BIGINT REFERENCES owners(id) ON DELETE SET NULL,

    CONSTRAINT cats_color_check CHECK (
                                          color::text = ANY (
                                          ARRAY[
                                          'BLACK'::VARCHAR,
                                          'WHITE'::VARCHAR,
                                          'GREY'::VARCHAR,
                                          'ORANGE'::VARCHAR,
                                          'SEMICOLOR'::VARCHAR,
                                          'BLACK_WHITE'::VARCHAR
    ]::TEXT[]
           )
    )
    );

CREATE TABLE IF NOT EXISTS friends (
                                              first_cat_id  BIGINT NOT NULL REFERENCES kotiki.cats(id) ON DELETE CASCADE,
    second_cat_id BIGINT NOT NULL REFERENCES kotiki.cats(id) ON DELETE CASCADE,
    PRIMARY KEY (first_cat_id, second_cat_id)
    );

CREATE TABLE IF NOT EXISTS users (
                                            username  VARCHAR(50) PRIMARY KEY,
    password  VARCHAR(255) NOT NULL,
    role      VARCHAR(20) NOT NULL,
    owner_id  BIGINT UNIQUE REFERENCES kotiki.owners(id) ON DELETE SET NULL,

    CONSTRAINT users_role_check CHECK (
                                          role::text = ANY (
                                          ARRAY[
                                          'USER'::VARCHAR,
                                          'ADMIN'::VARCHAR
    ]::TEXT[]
           )
    )
    );
