CREATE SCHEMA IF NOT EXISTS catsapp_owners;

CREATE TABLE IF NOT EXISTS catsapp_owners.owners (
    id    bigint GENERATED BY DEFAULT AS IDENTITY,
    first_name  varchar(255) NOT NULL,
    last_name   varchar(255) NOT NULL,
    birthdate   date,
    PRIMARY KEY (id)
);