server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5433/java
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.hikari.schema=catsapp_users

spring.jpa.hibernate.ddl-auto=update

spring.flyway.schemas=catsapp_users
spring.flyway.locations=classpath:/migrations
spring.flyway.validate-migration-naming=true

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=user
spring.rabbitmq.password=password
spring.rabbitmq.listener.simple.default-requeue-rejected=false